### ISSUE TITLE
'Invalid parameter: redirect_uri' Error

### ISSUE THREAD

**Issue by MarkAshraf96** [eclipse-tractusx/portal-assets#10]
Hello,

I have followed the steps in the ["Run frontend on localhost.md"](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/Run%20frontend%20on%20localhost.md).

1- On localhost:3001 or localhost:3002
I get the the error 'Invalid parameter: redirect_uri' and on inspecting the page I got this error 
```console
[Error] TypeError: null is not an object (evaluating 'document.getElementById('providers').firstChild')
	(anonymous function) (Main.js:273)
```
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/40201647/233325522-4668b614-5431-4e3c-b1f5-6bbaf6fc0c9e.png">

2- On localhost:3000
I get redirected to this [URL](https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/auth?client_id=Cl2-CX-Portal&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&state=72c9410d-eea9-4b64-8053-191fcf0ad8a6&response_mode=fragment&response_type=code&scope=openid&nonce=6bfdc02f-9858-4fa1-abe5-690940616d45&code_challenge=lo7IiQ-C3ptkBMO8_v0cf_4dG3vH6puAJBft4DFKiH8&code_challenge_method=S256), and I am not sure if that's the intended use case or not.

However, I found some worthy notes that I can contribute with in the previously mentioned URL on the UI/UX side, and I would like to know if I can arrange a short meetings with one of the maintainers.

**Comment by evegufy** [comment]
I think you need to adjust the default env specific values for your local setup and not use the default ones:
https://github.com/eclipse-tractusx/portal-frontend/blob/main/cx-portal/public/index.html#L33
https://github.com/eclipse-tractusx/portal-frontend-registration/blob/main/public/index.html#L36
Among others, for the centralidp.

But sure, it's possible to arrange a short meeting. If you want you can send me a (Teams) call for tomorrow afternoon.
Maybe we can also discuss https://github.com/eclipse-tractusx/portal-cd/issues/9.

**Comment by MarkAshraf96** [comment]
That would be great, is 2pm good for you?
And if you can send me your email, so I can create the meeting.

**Comment by evegufy** [comment]
As explained in todays call, I'll close the issue.
The 'Invalid parameter: redirect_uri' is expected when accessing localhost:3001 or localhost:3002 directly as the access is supposed to happen via the reverse proxy server at port 3000.
