### ISSUE TITLE
NoN: User Provisioning/SSO for Catena-X from an existing network (ext: CXAR-857)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-assets#100]
*Benefit Hypothesis:* 
After registration at a Catena-X operating company (either processed in an automated or manual way) from another network, the administrator of the business partner (BP) can provision users from the other network to Catena-X portal. Then the provisioned users can use single sign-on from the other network to Catena-X. This avoids double user administration (incl. deactivation) and user credential handling. 

*Acceptance Criteria:*
* The Catena-X Portal creates user accounts for the provisioned users from the other network.
* The Catena-X Portal allows single sign-on from another network. This other network is identity provider for the users from different BP managed by this other network.

_Components_: CPLP
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by jjeroch** [comment]
Duplicate with https://github.com/eclipse-tractusx/sig-release/issues/421
