### ISSUE TITLE
TRG 7.05 Legal information for distributions

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-assets#207]
For frontend components we recommend to add legal information next to your web content, e.g.:

```dockerfile
[...]
COPY LICENSE NOTICE.md DEPENDENCIES SECURITY.md /usr/share/nginx/html/
[...]
```

**Comment by evegufy** [comment]
@carslen up to now it wasn't clear that this TRG applies to frontend apps as well (due to [trg-7-06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) being place for frontend apps), but it's reasonable, so I implemented it.
