### ISSUE TITLE
TRG 7.06 Legal information for end user content

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-assets#208]
Where to find legal information for end users on Portal website? Please provide URL for verification, thank you.

**Comment by evegufy** [comment]
@carslen regarding implementation please see https://github.com/eclipse-tractusx/portal-frontend/issues/215#issuecomment-1683839179
If you'd like to the running implementation: I contacted you regarding screensharing in a bilateral chat.

**Comment by evegufy** [comment]
Screenshot of implementation:
![image](https://github.com/eclipse-tractusx/portal-assets/assets/46191613/e2be1bae-817e-43e0-89f3-470b158580b6)
