### ISSUE TITLE
TRG 2.03 repository structure

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-assets#210]
Do not use links to forks in product documentation: 

![grafik](https://github.com/eclipse-tractusx/portal-assets/assets/28647218/827fdc40-1aaf-4cb2-98aa-eba3802e93e9)

https://github.com/search?q=repo%3Aeclipse-tractusx%2Fportal-assets%20github.com%2Fcatenax-ng&type=code

**Comment by evegufy** [comment]
@carslen There's currently a clean up task ongoing to move all screenshots into the docs/static directory and reference from there. It'll be finished with the next release. Please annotate that accordingly in https://github.com/eclipse-tractusx/portal-assets/issues/205.

**Comment by carslen** [comment]
Links will be fixed with next release (24.03).
