### ISSUE TITLE
Help Application content missing

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-assets#232]
## Summary
After pr https://github.com/eclipse-tractusx/portal-assets/pull/226
likely the application app broke. 

Issue Env.: portal-rc.dev

Current screen:
<img width="549" alt="image" src="https://github.com/eclipse-tractusx/portal-assets/assets/94133633/aadf51bf-8be9-4ad9-bb4c-c13df376b4e0">

**Comment by evegufy** [comment]
This is expected for the (rc).dev env as the content isn't retrieved from a specific tag and the logic defaults to the main branch. In other words, the directory structure is already adjusted but not the content. Once the release branch for 1.8.0-rc2 gets merged into main, the content will match the new directory structure. Such an intermediate state can't occur on envs which running released versions, like int env, as a release always comes with a specific tag.

**Comment by evegufy** [comment]
The release branch for 1.8.0-rc2 gets has been merged into main.
