### ISSUE TITLE
Update Documentation for Clients/Technical Users

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-assets#335]
**Summary:**
The documentation for clients and technical users is out of date and needs to be reviewed and updated.

**Description:**
The current documentation located at the following link is out of date and needs to be reviewed and updated:

https://github.com/catenax-ng/tx-portal-assets/blob/main/docs/developer/Technical%20Documentation/DB%20Views%20and%20Details/Data%20Management.md

Please review the documentation and make any necessary updates to ensure the information is accurate and up-to-date. Additionally, explore if a better format or structure for the documentation can be identified to improve its usability for clients and technical users.

**Tasks:**
1. Review the existing documentation at the link provided.
2. Update the documentation to ensure all information is accurate and current.
3. Evaluate if a better format or structure for the documentation can be identified to enhance its usability while still ensuring those data to be available for users
4. Implement any necessary changes to the documentation
5. Validate the updated documentation and ensure it meets the needs of clients and technical users

**Acceptance Criteria:**
- The documentation is updated with accurate and current information.
- The documentation is presented in a format that is easy to navigate and understand for clients and technical users.
- The updated documentation is reviewed and approved

**Comment by evegufy** [comment]
done https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/03.%20Clients.md#initial-clients-and-service-accounts
