### ISSUE TITLE
sig#802: Documentation: Add Process Worker Documentation Section in Asset Repository

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-assets#351]
Description:
The scope of this ticket is to create a dedicated section under the 'developers' directory in our asset repository for documenting the details of process workers. This section should provide clear and comprehensive documentation on the role and functionality of each process worker, the processes they handle, and the specific details required for development and maintenance purposes.

Tasks:
1. Create a new directory named 'process_workers' under the existing 'developers' section in the asset repository.
2. Document the role of each process worker, including its purpose and the processes it handles.
3. Provide detailed descriptions of each process step, including inputs, outputs, and any relevant algorithms or business logic.
4. Outline any dependencies, such as external services or data sources, that the process workers interact with.
5. Ensure documentation includes code snippets, configuration details, and examples where necessary.
6. Review and validate the documentation for accuracy and completeness.

Acceptance Criteria:
- A new 'process_workers' section exists under the 'developers' directory in the asset repository.
- Documentation is clear, structured, and accessible, providing valuable insights into the process workers for new and existing team members.
- All documentation is reviewed for technical accuracy, clarity, and completeness.
- Code snippets and examples are tested to ensure they are correct and functional.

NOTE - the table created under https://github.com/eclipse-tractusx/portal-backend/issues/816 is expected to get documented as well

**Comment by MaximilianHauer** [comment]
@Phil91  did review the merged doc adjustment evtly you can push one behind that fixes some of my findings if they are valuable 
https://github.com/eclipse-tractusx/portal-assets/pull/368#pullrequestreview-2228574196
