### ISSUE TITLE
sig#805 - Align portal-assets documentation structure with updated TRG 1

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-assets#400]
### Description
To enhance the consistency and ease of understanding of our products for the open community, TRG 1 was updated.
Make sure to comply with the updated structure:

```
repository
└─── docs/
    └─── architecture/
    └─── admin/
    └─── user/
    └─── api/
    └─── README.md
```

Please TRG 1.05-1.08 for more information:
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-05 
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-06
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-07
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-08

### Acceptance Criteria

- [ ] Adjust the repo related documentation based on trg 1.05 - gather all architecture documentations into `docs/architecture`
- [ ] Adjust the repo related documentation based on trg 1.06 - gather admin related docu into `docs/admin`
- [ ] Adjust the repo related documentation based on trg 1.07 - gather end-user related documentation into `doc/user`
- [ ] Adjust the repo related documentation based on trg 1.08 - Clarify the setup with Evelyn ;) 
- [ ] Adjust the `docs/README.md` regarding your changes 
- [ ] Ensure that all documentation is in English

**Comment by MaximilianHauer** [comment]
@oyo  assigned it to you please take a look. we need to start with this TRG adjustments

**Comment by oyo** [comment]
@evegufy @MaximilianHauer currently we only have user and developer docs. So I suggest to rename developer to architecture and create empty folders for admin and api with README files saying content will follow (admin) or doesn't apply (api)

**Comment by MaximilianHauer** [comment]
sounds fine for me

**Comment by evegufy** [comment]
@oyo as discussed yesterday, there's architecture docs https://github.com/eclipse-tractusx/portal-assets/tree/v2.2.0/docs/developer/Technical%20Documentation
