### ISSUE TITLE
SSI - VC Creation Date must be set by issuer (Portal) (ext: CXAR-1038)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-assets#92]
+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: CPLP, MIW
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by jjeroch** [comment]
Closed, duplicate to the SSI Next 2.0 Implementation which was successfully delivered (including this request) in 24.05.
