### ISSUE TITLE
IAM: Maintenance Activities (ext: CXAR-1026)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-assets#94]
+*Benefit Hypothesis*+

IAM Maintenance
 * Keycloak
 ** Upgrade 2x.x (explore new KC functions and adapt to possible wins - such as setting new service account credentials)
 ** Get rid of import for initial setup
 ** Variable and secret management to be revisited
 ** User token lifespan revalidation and possible config update
 ** DB & Keycloak seeding - currently independent seeding - ideally this runs in sync/same data basis "file" to ensure that both have always the same set of data
 ** Keycloak lib unit tests to be rechecked
 ** Concept: Brokering one external idp for multiple companies
 ** Revisit: self service options inside the portal

 

 

+*Dependencies*+

The feature does not depend on any other feature.

Changes will apply to keycloak config, seeding logic, data migration/load, portal db seeding, portal db schema (regarding the one idp multiple companies) and probably a couple of api endpoints

 

+*Beneficiaries*+
platform operator, dataspace customers 

 

_Components_: CPLP
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by evegufy** [comment]
outdated
