### ISSUE TITLE
Portal - Marketplace: support best practices for categories (ext: CXAR-992)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-assets#97]
+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: CPLP
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
