### ISSUE TITLE
Portal - Network of Network - enable cross network registration (ext: CXAR-990)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-assets#98]
*+Problem statement (What problem shall be solved?) - Mandatory. 3 – 5 bullet points+*
 * In order to create the envisaged business value via apps it is necessary that many business partners (BP) of the supply chain are able to use these apps. CX starts with zero BP, but existing business networks already have many BPs.
 * CX is a new network on the market with the target to enable network to network collaboration (avoid silos).
 * With the first CX release network of network interoperability is only limited supported for productive usage because it requires separate registration for each network. This results in double registration and administration efforts for network customers.

 

*+Solution proposal (In which way will the problem be solved) - Mandatory. 3 – 5 bullet points+*
 * First step into the network to network connection
 ** The business network can trigger registrations of BPs on CX (incl. T&C acceptance for CX already on business network side)
 ** Those registration requests run through the normal approval flow of a company registration.  
 ** After registration the BP triggers provisioning of additional users from the business network to CX. 
 ** Now, its users can use single-sign on to CX. 
 * Next steps (out of scope of this issue) include further optimization of the integration as well as CXSOLUTION-155 Onboarding NoN: Enable customers to search for business partners in Network-of-Networks (NoN) - Jira (catena-x.net)

*+Benefit Hypothesis (What is the benefit of the solution) - Mandatory. 3 – 5 bullet points+*
 * Business networks leverage the CX usage by providing access of BP and users to CX.

*+Potential customers (who pays for the application) -Mandatory.+*
 * 1) BPs who want to reach a broad supplier base for their applications
 * 2) BPs who are on a business network and want to reuse their registration on the business network for CX
 * 3) Business network providers 

*+Potential user (e.g. purchaser, engineer) - Mandatory.+*
 * all users from a BP, mainly from the supplier side

*+Addressable market volume - Optional+*
 * for 1) dozens to hundreds 
 * for 2) ten thousands to many more
 * for 3) one to five

 

*+Validated with potential customers - Mandatory+*
 * Other networks

 

*+Risk - Optional+*
 * The production readiness of his solution holds under the assumption: There will be contracts between the customers of the network and the business network as well as contract between the business network and the OC. These contracts need to cover data sharing. However, a detailed legal assessment has not taken place yet.
 * Boundary conditions incl. business and price model of the OC are unknown, which could result in a not economically viable situation. Then the implemented solution is not used and the envisaged benefits are not realized.

 

+{*}Non-Functional Requirements (NFR){*}:+
 * _Performance_
 ** _Time Behaviour_
 ** _Resource Utilization_
 ** _Capacity_
 * _Scalability_
 ** _Property of the system to handle the growing amount of work by adding resources to the system_
 * _Resilience_
 ** _Ability to maintain an acceptable level of service in teh face of faults and challenges to normal operation_
 * _Serviceability_
 ** _How easy is it to perform service on the component or the whole system_
 * _Security_
 ** _Handling sensitive data_
 ** _Data Privacy aspects_

 
----
 

*Acceptance criteria / E2E-Tests:*

 

*E2E Test_01:*  Test registration via external network followed by login to CX.
*Assigned Team (proposal):*  Portal
*E2E Test Description:* A customer can trigger the C-X registration and has access to Catena-X afterwards (successful login test). The business network ID is auto-configured for the BP, furthermore the  business network and CX match the BPNs for the BPs.

 

 
----
 

_Components_: CPLP
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by jjeroch** [comment]
- [ ] https://github.com/eclipse-tractusx/portal-frontend/issues/470
